-- CreateEnum
CREATE TYPE "AdminRole" AS ENUM ('OWNER', 'ADMIN', 'STAFF');

-- CreateEnum
CREATE TYPE "InquiryStatus" AS ENUM ('NEW', 'CONTACTED', 'QUOTED', 'CONVERTED_TO_ORDER', 'CLOSED');

-- CreateEnum
CREATE TYPE "OrderType" AS ENUM ('CATALOG_PRODUCT', 'CUSTOM_INQUIRY');

-- CreateEnum
CREATE TYPE "PaymentOption" AS ENUM ('DEPOSIT_50', 'ONLINE_100');

-- CreateEnum
CREATE TYPE "PaymentStatus" AS ENUM ('PENDING', 'PAID', 'FAILED', 'CANCELLED', 'REFUNDED');

-- CreateEnum
CREATE TYPE "PaymentType" AS ENUM ('DEPOSIT', 'REMAINING_BALANCE', 'FULL_PAYMENT', 'SHIPPING_FEE');

-- CreateEnum
CREATE TYPE "ProofStatus" AS ENUM ('PENDING_REVIEW', 'VERIFIED', 'REJECTED');

-- CreateEnum
CREATE TYPE "ShipmentStatus" AS ENUM ('PENDING', 'READY_TO_SHIP', 'SHIPPED', 'IN_TRANSIT', 'DELIVERED', 'RETURNED', 'CANCELLED');

-- CreateEnum
CREATE TYPE "ContactStatus" AS ENUM ('NEW', 'IN_PROGRESS', 'RESOLVED', 'SPAM', 'ARCHIVED');

-- CreateEnum
CREATE TYPE "PageType" AS ENUM ('ABOUT', 'CONTACT', 'FAQ', 'ORDER_GUIDE', 'PAYMENT_GUIDE', 'SHIPPING_GUIDE', 'CUSTOM_PAGE');

-- CreateEnum
CREATE TYPE "SourceChannel" AS ENUM ('WEBSITE', 'ZALO', 'INSTAGRAM', 'TIKTOK', 'OTHER');

-- CreateEnum
CREATE TYPE "CustomsIdType" AS ENUM ('RESIDENCE_CARD', 'PASSPORT', 'VIRTUAL_ID', 'NONE');
